[package]
name = "substrate-api-client"
version = "2.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
rand = "0.7.1"
env_logger = "0.6"
ws = "0.7"
hex = "0.3"
log = "0.4"
clap = { version = "2.33", features = ["yaml"] }
serde = "1.0"
regex = "1.1"
serde_json = "1.0"
hex-literal = "0.1"
serde_derive = "1.0"
primitive-types = { version = "0.5", default-features = false, features = ["codec"] }
parity-codec-derive = { version = "3.3", default-features = false }

[dev-dependencies]
wabt = "0.9.0"

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate'

package = "substrate-primitives"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
features = ["derive"]
version = "1.0.0"

[dependencies.indices]
git = 'https://github.com/paritytech/substrate'

package = "srml-indices"

[dependencies.node-primitives]
git = 'https://github.com/paritytech/substrate'


[dependencies.runtime_io]
git = 'https://github.com/paritytech/substrate'

package = "sr-io"

[dependencies.transaction_pool]
git = 'https://github.com/paritytech/substrate'

package = "substrate-transaction-pool"

[dependencies.metadata]
git = 'https://github.com/paritytech/substrate'

package = "srml-metadata"

[dependencies.runtime_version]
git = 'https://github.com/paritytech/substrate'

package = "sr-version"

[dependencies.balances]
git = 'https://github.com/paritytech/substrate'

package = "srml-balances"

[dependencies.keyring]
git = 'https://github.com/paritytech/substrate'

package = "substrate-keyring"

[dependencies.system]
git = 'https://github.com/paritytech/substrate'

package = "srml-system"

[dependencies.runtime_primitives]
git = 'https://github.com/paritytech/substrate'

package = "sr-primitives"

[dependencies.runtime_support]
git = 'https://github.com/paritytech/substrate'

package = "srml-support"

[dev-dependencies.rstd]
git = 'https://github.com/paritytech/substrate'

package = "sr-std"

[dev-dependencies.node_runtime]
git = 'https://github.com/paritytech/substrate'

package = "node-runtime"

[dev-dependencies.test_node_runtime]
git = 'https://github.com/scs/substrate-test-nodes.git'
package = "test-node-runtime"

[dev-dependencies.contracts]
git = 'https://github.com/paritytech/substrate'
package = "srml-contracts"

[features]
default = ["std"]
std = [
	"primitives/std",
	"codec/std",
    "runtime_primitives/std",
]

[[example]]
name = "example_get_storage"
path = "src/examples/example_get_storage.rs"

[[example]]
name = "example_transfer"
path = "src/examples/example_transfer.rs"

[[example]]
name = "example_event_callback"
path = "src/examples/example_event_callback.rs"

[[example]]
name = "example_generic_extrinsic"
path = "src/examples/example_generic_extrinsic.rs"

[[example]]
name = "example_print_metadata"
path = "src/examples/example_print_metadata.rs"

[[example]]
name = "example_contract"
path = "src/examples/example_contract.rs"

[[example]]
name = "example_custom_storage_struct"
path = "src/examples/example_custom_storage_struct.rs"

[[example]]
name = "example_create_identity"
path = "src/examples/example_create_identity.rs"

[[example]]
name = "example_create_token"
path = "src/examples/example_create_token.rs"

